import { array, boolean, digest, enumeration, id, integer, literal, object, optional, pageSize, ref, text, union } from './schema.js';

const empty = object({});
const page = object({ after: optional(integer), limit: optional(pageSize) });
const execution = object({ execution: ref('execution') });
const task = object({ task: ref('task') });
const operation = object({ operation: ref('operation') });
const proposal = object({ proposal: ref('proposal'), digest });
const destination = text;
// These references resolve approved/inspected immutable data, never arbitrary executable JSON.
// Their full domain records are produced by P0M2/P0M3/P0M4 and the named service owner.
const document = object({ revision: integer, digest, text });
const setting = object({ key: text, value: union(text, integer, boolean, literal(null)) });

function action<const K extends 'query' | 'command' | 'internal', S>(kind: K, owner: string, scope: 'user' | 'project', payload: S, producer = 'P0M1') {
  return Object.freeze({ kind, owner, scope, payload, payloadProducer: producer, resultEnvelope: kind === 'query' ? 'query-watermark-v1' as const : 'command-result-v1' as const, resultPayloadProducer: owner, implemented: false as const, partition: 'H' as const });
}
/** Exact H catalog. Entries declare contracts, not installed handlers or authority grants. */
export const catalog = Object.freeze({
  'core.start': action('command', 'P3M0', 'user', empty),
  'core.status': action('query', 'P3M0', 'user', empty),
  'core.stop': action('command', 'P3M0', 'user', empty),
  'protocol.handshake': action('query', 'P3M1', 'user', empty),
  'capability.query': action('query', 'P3M1', 'user', empty),
  'command.outcome': action('query', 'P1M1', 'user', object({ commandId: id('command') })),
  'snapshot.query': action('query', 'P1M3', 'project', page),
  'events.query': action('query', 'P1M3', 'project', object({ after: integer, limit: pageSize })),
  'project.create': action('command', 'P1M2', 'user', object({ sourceRoot: text, name: text })),
  'project.adopt': action('command', 'P5M0', 'user', object({ sourceRoot: text, name: text })),
  'project.gitInit': action('command', 'P5M0', 'project', object({ binding: ref('binding'), branch: text })),
  'project.status': action('query', 'P11M1', 'project', empty),
  'project.start': action('command', 'P9M2', 'project', execution),
  'project.pause': action('command', 'P9M4', 'project', execution),
  'project.resume': action('command', 'P9M2', 'project', execution),
  'task.cancel': action('command', 'P9M4', 'project', task),
  'project.stop': action('command', 'P9M4', 'project', execution),
  'project.reopen': action('command', 'P9M8', 'project', object({ parent: ref('execution'), baseline: enumeration(['accepted-result', 'source']), confirmSourceDivergence: boolean }), 'P0M4'),
  'specification.query': action('query', 'P6M0', 'project', execution),
  'specification.propose': action('command', 'P6M0', 'project', object({ execution: ref('execution'), document }), 'P0M2'),
  'interview.begin': action('command', 'P6M1', 'project', execution),
  'interview.answer': action('command', 'P6M1', 'project', object({ operation: ref('operation'), answer: text })),
  'interview.cancel': action('command', 'P6M1', 'project', operation),
  'interview.abandon': action('command', 'P6M0', 'project', execution),
  'interview.restart': action('command', 'P6M0', 'project', execution),
  'interview.status': action('query', 'P6M1', 'project', execution),
  'roadmap.query': action('query', 'P6M2', 'project', execution),
  'roadmap.generate': action('command', 'P6M2', 'project', object({ specification: ref('specification') })),
  'roadmap.propose': action('command', 'P6M2', 'project', object({ execution: ref('execution'), document }), 'P0M2'),
  'mutation.preview': action('query', 'P6M3', 'project', proposal),
  'mutation.propose': action('command', 'P6M3', 'project', object({ roadmap: ref('roadmap'), document, reason: text }), 'P0M2'),
  'approval.query': action('query', 'P1M1', 'project', page),
  'approval.approve': action('command', 'P9M7', 'project', object({ approval: ref('approval'), proposalDigest: digest }), 'P0M3'),
  'approval.deny': action('command', 'P9M7', 'project', object({ approval: ref('approval'), proposalDigest: digest, reason: text }), 'P0M3'),
  'settings.query': action('query', 'P1M4', 'project', empty),
  'settings.update': action('command', 'P1M4', 'project', object({ changes: array(setting) }), 'P0M4'),
  'settings.clearOverride': action('command', 'P1M4', 'project', object({ keys: array(text) }), 'P0M4'),
  'settings.defaults.query': action('query', 'P1M4', 'user', empty),
  'settings.defaults.update': action('command', 'P1M4', 'user', object({ changes: array(setting) }), 'P0M4'),
  'settings.effective': action('query', 'P1M4', 'project', object({ snapshot: optional(ref('snapshot')) }), 'P0M4'),
  'settings.correction.preview': action('query', 'P1M4', 'project', object({ operation: ref('operation'), changes: array(setting) }), 'P0M4'),
  'settings.correctHeldRole': action('command', 'P9M6', 'project', object({ operation: ref('operation'), candidate: ref('candidate'), candidateDigest: digest, proposal: ref('proposal'), proposalDigest: digest, approval: ref('approval') }), 'P0M4'),
  'decisions.query': action('query', 'P1M5', 'project', page),
  'decision.record': action('command', 'P1M5', 'project', object({ text, source: text, scope: text }), 'P0M2'),
  'decision.supersede': action('command', 'P1M5', 'project', object({ previous: ref('decision'), text, reason: text }), 'P0M2'),
  'trust.query': action('query', 'P2M0', 'project', empty),
  'trust.grant': action('command', 'P2M0', 'project', object({ proposal: ref('proposal'), digest, approval: ref('approval') }), 'P0M3'),
  'trust.revoke': action('command', 'P2M0', 'project', object({ grant: ref('grant') }), 'P0M3'),
  'secretReference.authorize': action('command', 'P2M1', 'project', object({ reference: text, operation: ref('operation'), approval: ref('approval') }), 'P0M3'),
  'secretReference.revoke': action('command', 'P2M1', 'project', object({ grant: ref('grant') }), 'P0M3'),
  'worker.status': action('query', 'P11M1', 'project', task),
  'worker.retry': action('command', 'P9M3', 'project', object({ task: ref('task'), strategy: ref('proposal'), digest })),
  'validation.status': action('query', 'P11M1', 'project', operation),
  'validation.cancel': action('command', 'P9M4', 'project', operation),
  'validation.retry': action('command', 'P7M4', 'project', object({ operation: ref('operation'), remediation: ref('proposal'), digest }), 'P0M4'),
  'renewal.status': action('query', 'P7M6', 'project', object({ renewal: ref('renewal') })),
  'renewal.drain': action('internal', 'P9M0', 'project', execution),
  'renewal.execute': action('internal', 'P7M6', 'project', object({ renewal: ref('renewal'), candidate: ref('candidate') }), 'P0M4'),
  'repair.status': action('query', 'P6M4', 'project', object({ repair: ref('repair') })),
  'repair.propose': action('command', 'P6M4', 'project', object({ repair: ref('repair'), document }), 'P0M4'),
  'repair.admit': action('internal', 'P9M0', 'project', object({ repair: ref('repair'), approval: ref('approval'), digest }), 'P0M4'),
  'results.query': action('query', 'P8M1', 'project', execution),
  'results.diff': action('query', 'P8M1', 'project', object({ candidate: ref('candidate'), after: optional(integer) })),
  'results.export': action('command', 'P8M1', 'project', object({ execution: ref('execution'), destination })),
  'usage.query': action('query', 'P10M0', 'project', empty),
  'power.query': action('query', 'P10M2', 'user', empty),
  'master.request': action('command', 'P11M0', 'project', object({ execution: ref('execution'), text })),
  'master.status': action('query', 'P11M0', 'project', operation),
  'master.cancel': action('command', 'P11M0', 'project', operation),
  'deferred.query': action('query', 'P11M0', 'project', execution),
  'deferred.set': action('command', 'P11M0', 'project', object({ target: union(ref('task'), ref('phase')), action: literal('pause') })),
  'deferred.cancel': action('command', 'P11M0', 'project', object({ control: ref('deferred') })),
  'diagnostics.query': action('query', 'P10M3', 'project', page),
  'diagnostics.retention': action('query', 'P1M6', 'project', empty),
  'diagnostics.export': action('command', 'P10M3', 'project', object({ destination })),
  'diagnostics.deleteOptional': action('command', 'P10M3', 'project', object({ inspectedSnapshot: ref('snapshot'), digest })),
  'history.purge': action('command', 'P1M6', 'project', object({ inspectedSnapshot: ref('snapshot'), digest, approval: ref('approval') })),
  'maintenance.run': action('command', 'P10M3', 'project', object({ proposal: ref('proposal'), digest })),
  'identity.inspect': action('query', 'P1M2', 'user', object({ sourceRoot: text })),
  'identity.relink': action('command', 'P1M2', 'project', object({ binding: ref('binding'), destination, inspectedDigest: digest })),
  'identity.copyAsNew': action('command', 'P1M2', 'user', object({ sourceRoot: text, name: text, inspectedDigest: digest })),
  'portable.conflicts': action('query', 'P1M3', 'project', page),
  'portable.importProposal': action('command', 'P6M3', 'project', object({ projection: ref('projection'), inspectedDigest: digest })),
  'portable.exportNew': action('command', 'P1M3', 'project', object({ projection: ref('projection'), destination })),
  'portable.replaceInspected': action('command', 'P1M3', 'project', object({ projection: ref('projection'), inspectedDigest: digest, approval: ref('approval') })),
  'portable.repair': action('command', 'P1M3', 'project', operation),
  'lifecycle.sponsored': action('query', 'P10M4', 'user', empty),
  'lifecycle.transfer': action('command', 'P10M4', 'project', object({ execution: ref('execution'), principal: id('principal') })),
  'lifecycle.background': action('command', 'P10M4', 'project', object({ execution: ref('execution'), value: enumeration(['pause', 'keep-running']) })),
  'client.quit': action('command', 'P10M4', 'user', object({ principal: id('principal'), observed: array(object({ execution: ref('execution'), revision: integer })) })),
  'execution.query': action('query', 'P11M1', 'project', execution),
  'phase.query': action('query', 'P11M1', 'project', object({ phase: ref('phase') })),
  'task.query': action('query', 'P11M1', 'project', task),
  'attempt.query': action('query', 'P11M1', 'project', object({ attempt: ref('attempt') })),
  'holds.query': action('query', 'P11M1', 'project', execution),
  'report.query': action('query', 'P11M1', 'project', object({ phase: ref('phase') })),
  'recovery.status': action('query', 'P10M1', 'project', empty),
  'recovery.reconcile': action('command', 'P10M1', 'project', object({ operation: ref('operation'), proposal: ref('proposal'), digest })),
});
export type ActionId = keyof typeof catalog;
export const clientBindings = Object.freeze([
  { id: 'activation', owner: 'P12M2', invokes: ['protocol.handshake', 'capability.query', 'snapshot.query', 'events.query'] },
  { id: 'navigation', owner: 'P12M3', invokes: ['project.status'] },
  { id: 'editor.window.presentation', owner: 'P12M3', invokes: [] },
  { id: 'onboarding.presentationPreference', owner: 'P13M0', invokes: ['project.create', 'project.adopt', 'project.gitInit'] },
  { id: 'surface.render.focus', owner: 'P13M10', invokes: ['roadmap.query', 'report.query', 'master.status', 'project.status'] },
  { id: 'shellLauncher.install', owner: 'P12M1', invokes: [] },
  { id: 'gallery', owner: 'P14M0', invokes: ['settings.query', 'settings.update'] },
  { id: 'optionalTelemetry.transport', owner: 'P14M1', invokes: ['settings.query', 'diagnostics.query'] },
] satisfies readonly { id: string; owner: string; invokes: ActionId[] }[]);
export const partitions = Object.freeze({
  H: { schemaVersion: 1, capabilityVersion: 1, implementedOperations: [] as ActionId[], owner: 'P11M4' },
  I: { schemaVersion: 1, capabilityVersion: 0, implementedOperations: [] as string[], owner: 'P12M2' },
  U: { schemaVersion: null, capabilityVersion: null, implementedOperations: [], payloadOwner: 'P15M0', owner: 'P15M4' },
  L: { schemaVersion: null, capabilityVersion: null, implementedOperations: [], authority: 'maintainer-only', owner: 'P15M4' },
});
